//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedLibrary.Resources.Languages.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring social settings.
        /// </summary>
        internal static string Acquiring_social_settings {
            get {
                return ResourceManager.GetString("Acquiring social settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying social settings.
        /// </summary>
        internal static string Applying_social_settings {
            get {
                return ResourceManager.GetString("Applying social settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with database established.
        /// </summary>
        internal static string Connection_with_database_established {
            get {
                return ResourceManager.GetString("Connection with database established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with server established.
        /// </summary>
        internal static string Connection_with_server_established {
            get {
                return ResourceManager.GetString("Connection with server established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing login.
        /// </summary>
        internal static string Initializing_login {
            get {
                return ResourceManager.GetString("Initializing login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging with {0}.
        /// </summary>
        internal static string Logging_with__0_ {
            get {
                return ResourceManager.GetString("Logging with {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with.
        /// </summary>
        internal static string Login_with {
            get {
                return ResourceManager.GetString("Login with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with credentials.
        /// </summary>
        internal static string Login_with_credentials {
            get {
                return ResourceManager.GetString("Login with credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        internal static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting from server the login URL with {0}.
        /// </summary>
        internal static string Requesting_from_server_the_login_URL_with__0_ {
            get {
                return ResourceManager.GetString("Requesting from server the login URL with {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social settings applied.
        /// </summary>
        internal static string Social_settings_applied {
            get {
                return ResourceManager.GetString("Social settings applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed.
        /// </summary>
        internal static string Task_completed {
            get {
                return ResourceManager.GetString("Task completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task started.
        /// </summary>
        internal static string Task_started {
            get {
                return ResourceManager.GetString("Task started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying connections.
        /// </summary>
        internal static string Verifying_connections {
            get {
                return ResourceManager.GetString("Verifying connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for server reply.
        /// </summary>
        internal static string Waiting_for_server_reply {
            get {
                return ResourceManager.GetString("Waiting for server reply", resourceCulture);
            }
        }
    }
}
